<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="img-rounded" src="<?php echo $this->basePath('img/1.fw.png') ?>" alt="TCA">
            <div class="carousel-caption">
                <p style="font-size: 100px"><b>BIENVENIDOS</b></p>
                <p style="font-size: 50px"><i class="fa fa-5x fa-university" aria-hidden="true"></i></p>
            </div>
        </div>
        <div class="item ">
            <img class="img-rounded" src="<?php echo $this->basePath('img/2.fw.png') ?>" alt="law">
            <div class="carousel-caption">
                <p style="font-size: 100px"><b>SALA "A"</b></p>
                <p style="font-size: 50px"><i class="fa fa-5x fa-long-arrow-left" aria-hidden="true"></i></p>
            </div>
        </div>
        <div class="item ">
            <img class="img-rounded" src="<?php echo $this->basePath('img/3.fw.png') ?>" alt="law">
            <div class="carousel-caption">
                <p style="font-size: 100px"><b>SALA "B"</b></p>
                <p style="font-size: 50px"><i class="fa fa-5x fa-long-arrow-right" aria-hidden="true"></i></p>
            </div>
        </div>
        <div class="item ">
            <img class="img-rounded" src="<?php echo $this->basePath('img/11.fw.png') ?>" alt="law">
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>